version: "3"
services:
  db:
    container_name: 'db'
    image: 'mysql'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'obada5781obada123'
      MYSQL_DATABASE: 'school'

    volumes:
      - cr-data:/var/lib/postgresql/data
    networks:
      - 'mynet'

  app:
    container_name: 'cr'
    image: 'cr'
    build: .
    restart: 'on-failure'
    ports:
      - '8080:8080'
    environment:
      DB_HOST: 'db'
      DB_USER: 'root'
      DB_PASSWORD: 'obada5781obada123'
      DB_PORT: '3306'
      DB_NAME: 'school'
    networks:
      - 'mynet'
    depends_on:
      - 'db'
networks:
  mynet:
    external: true
volumes:
  cr-data: